name: Finality
version: '1.0-SNAPSHOT'
main: org.fracturedsmp.finality.Finality
api-version: '1.21'
commands:
  plotarmor:
    description:
    usage: /<command> <add|remove|list> [player]
    aliases: [pltamr]
